name: github_search_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1


  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  google_fonts: ^4.0.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^2.1.1
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true

assets:
